name: Build SEA

on:
  workflow_call:
    inputs:
      fetchPackageJson:
        description: Fetch package.json from artifacts
        type: boolean
  workflow_dispatch:

jobs:
  build-sea:
    runs-on: windows-latest # We need Windows (or Wine) to use rcedit (to update the .exe's properties)

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download package.json
        uses: actions/download-artifact@v4
        with:
          name: package-json

      - name: Install dependencies
        run: npm ci

      # Build with new name and version
      - name: Build binaries
        run: ./node_modules/.bin/ts-node tools/build-binaries.ts

      - name: Upload build artifact
        if: ${{ inputs.fetchPackageJson }}
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            dist/server.js
            dist/smtp2graph-*
          if-no-files-found: error