name: Basic tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run standard tests
        run: npm run test:receive -- --reporter json --reporter-option output=test-results.json

      - name: Test report
        uses: phoenix-actions/test-reporting@v12
        if: success() || failure()
        with:
          name: Test result
          path: test-results.json
          reporter: mocha-json

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: logs
          path: logs/
          if-no-files-found: ignore